POST http://ec2-35-178-178-115.eu-west-2.compute.amazonaws.com/api/blogs 
content-type: application/json

{
    "title": "Test title blog 3",
    "author": "He being himself",
    "url": "some-random-url.org",
    "likes": 12,
    "userId": "653a353a580c8d54ed36bd98"
}