POST http://ec2-35-178-178-115.eu-west-2.compute.amazonaws.com/api/login
content-type: application/json
Authorization: Bearer yJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5vdFJvb3QiLCJpZCI6IjY1M2E4NTE1MDQxODEyYTM2NTY3N2QzZCIsImlhdCI6MTY5ODgyNTg5MiwiZXhwIjoxNjk4ODI5NDkyfQ.WtA08Gfmh4ylalMznJC0eu1hSRtzrBTtXpPQDYK_834

{
    "username": "notRoot",
    "password": "zielonekorale"
}

# {
#     "username": "root",
#     "password": "kiloogorkow"
# }